/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sample.kafkastreamjoin.model_avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SubjectKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8258039263998626776L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SubjectKey\",\"namespace\":\"com.sample.kafkastreamjoin.model_avro\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SubjectKey> ENCODER =
      new BinaryMessageEncoder<SubjectKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SubjectKey> DECODER =
      new BinaryMessageDecoder<SubjectKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SubjectKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SubjectKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SubjectKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SubjectKey>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SubjectKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SubjectKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SubjectKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SubjectKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SubjectKey() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   */
  public SubjectKey(java.lang.Integer id) {
    this.id = id;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Creates a new SubjectKey RecordBuilder.
   * @return A new SubjectKey RecordBuilder
   */
  public static com.sample.kafkastreamjoin.model_avro.SubjectKey.Builder newBuilder() {
    return new com.sample.kafkastreamjoin.model_avro.SubjectKey.Builder();
  }

  /**
   * Creates a new SubjectKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SubjectKey RecordBuilder
   */
  public static com.sample.kafkastreamjoin.model_avro.SubjectKey.Builder newBuilder(com.sample.kafkastreamjoin.model_avro.SubjectKey.Builder other) {
    if (other == null) {
      return new com.sample.kafkastreamjoin.model_avro.SubjectKey.Builder();
    } else {
      return new com.sample.kafkastreamjoin.model_avro.SubjectKey.Builder(other);
    }
  }

  /**
   * Creates a new SubjectKey RecordBuilder by copying an existing SubjectKey instance.
   * @param other The existing instance to copy.
   * @return A new SubjectKey RecordBuilder
   */
  public static com.sample.kafkastreamjoin.model_avro.SubjectKey.Builder newBuilder(com.sample.kafkastreamjoin.model_avro.SubjectKey other) {
    if (other == null) {
      return new com.sample.kafkastreamjoin.model_avro.SubjectKey.Builder();
    } else {
      return new com.sample.kafkastreamjoin.model_avro.SubjectKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for SubjectKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SubjectKey>
    implements org.apache.avro.data.RecordBuilder<SubjectKey> {

    private int id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sample.kafkastreamjoin.model_avro.SubjectKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing SubjectKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sample.kafkastreamjoin.model_avro.SubjectKey other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.sample.kafkastreamjoin.model_avro.SubjectKey.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.sample.kafkastreamjoin.model_avro.SubjectKey.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SubjectKey build() {
      try {
        SubjectKey record = new SubjectKey();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SubjectKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<SubjectKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SubjectKey>
    READER$ = (org.apache.avro.io.DatumReader<SubjectKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










